import { StyleSheet } from 'react-native';

export default StyleSheet.create({

    // Login Welcome Page styles
    input: {                                        // Login/Welcome page input field styles
        fontSize: 15,
        width: 240,
        height: 40,
        position: 'absolute',
        right: 40,
        bottom: 1,
        borderColor: '#c4c4c4',
        borderBottomWidth: 1,
    },
    inputBox: {
        height: 50,
        width: 310,
        marginTop: 5,
        backgroundColor: '#1e628e',
        borderColor: '#1c5a82',
        borderWidth: 5,
        borderTopWidth: 0,
        borderLeftWidth: 0,
        borderTopLeftRadius: 40,
        borderBottomRightRadius: 40,
        shadowColor: '#1c5a82',
        shadowOffset: { width: 2, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    keyview: {                                      // keyboard avoiding view styles
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-between'
    },
    loginBTN: {                                    // Not Yet button style
        backgroundColor: '#56b973',
        borderWidth: 2,
        borderColor: '#4ca466',
        borderRadius: 40,
        shadowColor: '#00ace6',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        marginLeft: 5,
        marginRight: 5,
        marginTop: 20,
        padding: 10,
        width: 200,
        alignItems: 'center',
    },
    
    // Global styles
    containerFlex: {                                // container with justify content center
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    container: {                                    // container "without"
        flex: 1,
        alignItems: 'center',
        backgroundColor: 'transparent'
    },
    logo: {                                         // logo styles for header image
        flex: 1,
        resizeMode: 'contain',
        width: "100%",
    },
    box: {                                          // box styles for graphs
        flex: 1,
        justifyContent: 'center',
        height: 225,
        width: 325,
        backgroundColor: '#f7ffeb',
        borderColor: '#c7c7c7',
        borderWidth: 5,
        borderRadius: 15,
        shadowColor: '#e0e0e0',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 5,
        margin: 5,
        marginBottom: 15,
    },
    boxSmall: {                                    // box styles for graph data lables
        alignItems: 'center',
        height: 150,
        width: 150,
        backgroundColor: '#e6e6e6',
        borderBottomLeftRadius: 60,
        borderRadius: 10,
        borderBottomRightRadius: 5,
        borderWidth: 5,
        borderTopWidth: 0,
        borderRightWidth: 0,
        borderColor: '#c7c7c7',
        shadowColor: 'black',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 5,
        elevation: 10,
        margin: 10,
        padding: 10,
    },
    smallText: {                                   // size 15 text
        fontSize: 18,
    },
    smallTextS: {                                   // size 15 text
        fontSize: 18,
        color: '#d1d1d1',
    },
    mediumText: {
        fontSize: 35,
        color: '#d1d1d1',
    },
    mediumTextS: {                                  // size 55 text
        fontSize: 55,
        color: '#878787',
        paddingTop: 10,
    },
    mediumTextY: {
        fontSize: 55,
        paddingTop: 10,
        color: '#ffa600',
    },
    mediumTextB: {
        fontSize: 55,
        paddingTop: 10,
        color: '#0095ff',
    },
    podLog: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 50,
        marginBottom: 30,
    },
    boxGraph: {                                     // graph style
        height: 225,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
    },
    btnOG: {                                        // Button Outline Green
        backgroundColor: 'white',
        borderRadius: 15,
        shadowColor: '#397b4c',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 1,
        marginLeft: 5,
        marginRight: 5,
        marginTop: 10,
        padding: 10,
        paddingRight: 50,
        paddingLeft: 50,
    },
    btnOR: {                                         // Button Outline Red
        backgroundColor: 'white',
        borderRadius: 15,
        shadowColor: '#990000',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 1,
        marginLeft: 5,
        marginRight: 5,
        marginTop: 10,
        padding: 10,
        paddingRight: 50,
        paddingLeft: 50,
    },
    logoutBtn: {                                    // Logout Button style
        backgroundColor: '#60ce80',
        borderWidth: 2,
        borderColor: '#56b973',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        shadowColor: '#5ce68a',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        marginLeft: 5,
        marginRight: 5,
        marginBottom: 10,
        padding: 10,
        paddingRight: 100,
        paddingLeft: 100,
    },
    notyetBtn: {                                    // Not Yet button style
        backgroundColor: '#227cb5',
        borderWidth: 3,
        borderColor: '#2175aa',
        borderBottomRightRadius: 30,
        borderBottomLeftRadius: 30,
        shadowColor: '#00ace6',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        marginLeft: 5,
        marginRight: 5,
        marginTop: 20,
        padding: 10,
        paddingRight: 100,
        paddingLeft: 100,
    },
    timeBTN1: {                                // time from button style
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#00bfff',
        borderWidth: 2,
        borderColor: '#00aae3',
        borderTopRightRadius: 40,
        borderBottomLeftRadius: 40,
        borderRadius: 0,
        shadowColor: '#00ace6',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        marginTop: 10,
        marginBottom: 5,
        margin: 10,
        padding: 10,
        width: 150,
    },
    timeBTN2: {                                   // time to button style
        alignItems: 'center',
        backgroundColor: '#00bfff',
        borderWidth: 3,
        borderColor: '#00aae3',
        borderTopLeftRadius: 40,
        borderBottomRightRadius: 40,
        borderRadius: 0,
        shadowColor: '#00ace6',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        margin: 10,
        marginTop: 10,
        marginBottom: 5,
        padding: 10,
        width: 150,
    },
    runScheduleBTN: {                               // Start schedule btn style
        alignItems: 'center',
        backgroundColor: '#60ce80',
        borderWidth: 3,
        borderColor: '#56b973',
        borderRadius: 20,
        shadowColor: '#397b4c',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        margin: 10,
        marginTop: 10,
        marginBottom: 20,
        padding: 10,
        width: 325,
    },
    testRunBTN: {                                  // test run btn style
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cfcfcf',
        borderColor: '#c2c2c2',
        borderWidth: 7,
        borderRadius: 40,
        shadowColor: '#397b4c',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        margin: 10,
        marginBottom: 0,
        padding: 10,
        width: 145,
        height: 65,
    },
    lightsBTN: {                                   // lights on/off btn style
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#cfcfcf',
        borderColor: '#c2c2c2',
        borderWidth: 7,
        borderRadius: 40,
        shadowColor: '#397b4c',
        shadowOffset: { width: 1, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 10,
        margin: 10,
        marginBottom: 0,
        padding: 10,
        width: 145,
        height: 65,
    },
    greyText: {                                         // global grey text
        color: '#e6e6e6',
        textAlign: 'center',
        fontSize: 20,
        marginBottom: 20
    },
    hasErrors: {
        borderBottomColor: 'red',
    }
})